name: Update Schema Weekly

on:
  schedule:
    - cron: "0 3 * * 1" # æ¯å‘¨ä¸€ UTC+3
  workflow_dispatch: # æ‰‹åŠ¨è§¦å‘

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download schema file
        run: |
          gh release download --repo poe-tool-dev/dat-schema --pattern "*.json*"
      # - name: Download schema file
      #   run: |
      #     echo "Downloading latest schema..."
      #     curl -L -o schema.jsonl https://github.com/poe-tool-dev/dat-schema/releases/download/latest/schema.jsonl
      #     ls -lh schema.jsonl
      #     head -c 100 schema.jsonl || true

      - name: Commit and push if changed or new
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "ğŸ“ Detected new or changed schema.jsonl, committing..."
          git rm -r --cached .
          git add --force ./
          git commit -m "chore: update schema.jsonl ($(date -u +"%Y-%m-%d %H:%M:%S UTC"))"
          git push --force
